const Data = [
  {
    id: 1,
    image: "../../assets/p1.png",
    name: "Gap",
    category: "sweatshirts",
    price: 1200,
    discount_price: 599,
    description: "Men's Pullover Sweattshirt",
  },
  {
    id: 2,
    image: "../../assets/p2.png",
    name: "Puma",
    category: "tee shirt",
    price: 1200,
    discount_price: 599,
    description: "Solid Polo Collar Grey T-shirt",
  },
  {
    id: 3,
    image: "../../assets/p3.png",
    name: "U.S. Polo Assn.",
    category: "shirt",
    price: 400,
    discount_price: 199,
    description: "Men Blue regular fit Striped casual Shirt",
  },
  {
    id: 4,
    image: "../../assets/p4.png",
    name: "Here & now",
    category: "jacket",
    price: 1000,
    discount_price: 500,
    description: "Men blue solid biker jacket",
  },
  {
    id: 5,
    image: "../../assets/p5.png",
    name: "Roadster",
    category: "jacket",
    price: 1200,
    discount_price: 600,
    description: "Men red solid padded jacket",
  },
  {
    id: 6,
    image: "../../assets/p6.png",
    name: "Roadster",
    category: "shirt",
    price: 1200,
    discount_price: 599,
    description: "Men black & red Regular fit checked shirt",
  },
  {
    id: 7,
    image: "../../assets/p7.png",
    name: "Wrong",
    category: "shirt",
    price: 1200,
    discount_price: 599,
    description: " Men Navy Blue Slim Fit Checked Casu...",
  },
  {
    id: 8,
    image: "../../assets/p8.png",
    name: "Mast & Harbour",
    category: "sweatshirts",
    price: 1200,
    discount_price: 599,
    description: "Men brown cable knit sweater",
  },
  {
    id: 9,
    image: "../../assets/p9.png",
    name: "Jack & Jones",
    category: "tee shirt",
    price: 1200,
    discount_price: 599,
    description: "Men Green Slim Fit Printed Round Ne...",
  },
  {
    id: 10,
    image: "../../assets/p10.png",
    name: "U.S. Polo Assn.",
    category: "polo tee shirt",
    price: 1200,
    discount_price: 599,
    description: "Men Green & Blue Striped Polo Collar...",
  },
  {
    id: 11,
    image: "../../assets/p11.jpg",
    name: "U.S. Polo Assn.",
    category: "polo tee shirt",
    price: 1200,
    discount_price: 599,
    description: "Men Green & Blue Striped Polo Collar...",
  },
  {
    id: 12,
    image: "../../assets/p12.jpg",
    name: "Roadster",
    category: "tee shirt",
    price: 1200,
    discount_price: 599,
    description: "Men white checked polo collar T-Shirt ",
  },
  {
    id: 13,
    image: "../../assets/p13.jpg",
    name: "Roadster",
    category: "shirt",
    price: 1200,
    discount_price: 599,
    description: "Men navy blue & grey regular fit checked",
  },
  {
    id: 14,
    image: "../../assets/p14.jpg",
    name: "Jack & Jones",
    category: "tshirt",
    price: 1200,
    discount_price: 599,
    description: "Men purple regular fit printed casual shirt",
  },
  {
    id: 15,
    image: "../../assets/p15.jpg",
    name: "Gap",
    category: "tshirt",
    price: 1200,
    discount_price: 599,
    description: "Men red regular fit printed casual shirt",
  },
  {
    id: 16,
    image: "../../assets/p16.jpg",
    name: "Mast & Harbour",
    category: "denim",
    price: 1200,
    discount_price: 599,
    description: "Men grey slim fit faded casual Denim shirt",
  },
  {
    id: 17,
    image: "../../assets/p17.jpg",
    name: "Highlander",
    category: "denim",
    price: 1200,
    discount_price: 599,
    description: "Men blue slim fit solid casual denim shirt",
  },
  {
    id: 18,
    image: "../../assets/p18.jpg",
    name: "Roadster",
    category: "denim",
    price: 400,
    discount_price: 199,
    description: "Men blue regular fit solid casual denim shirt",
  },
  {
    id: 19,
    image: "../../assets/p19.jpg",
    name: "Gap",
    category: "tshirt",
    price: 1000,
    discount_price: 500,
    description: "Men grey & blue logo contrast re",
  },
  {
    id: 20,
    image: "../../assets/p20.jpg",
    name: "Gap",
    category: "tshirt",
    price: 1200,
    discount_price: 600,
    description: "Men's Pullover Sweattshirt",
  },
  {
    id: 21,
    image: "../../assets/p21.jpg",
    name: "Tommy Hilfiger",
    category: "tee shirt",
    price: 1200,
    discount_price: 599,
    description: "Men Navy Blue Printed Round Neck T...",
  },
  {
    id: 22,
    image: "../../assets/p22.jpg",
    name: "Here&Now",
    category: "tee shirt",
    price: 1200,
    discount_price: 599,
    description: "Men Teal Blue & Black Printed Round N...",
  },
  {
    id: 23,
    image: "../../assets/p23.jpg",
    name: "Difference of Opinion ",
    category: "tee shirt",
    price: 1200,
    discount_price: 599,
    description: "Men Sea Green Solid Round Neck T-sh...",
  },

  {
    id: 24,
    image: "../../assets/p24.jpg",
    name: "Maniac ",
    category: "tee shirt",
    price: 1200,
    discount_price: 599,
    description: "Men Navy Blue Printed Round Neck T...",
  },
  {
    id: 25,
    image: "../../assets/p25.jpg",
    name: "HRX by Hrithik Roshan ",
    category: "tee shirt",
    price: 1200,
    discount_price: 599,
    description: "Men Navy Blue Solid Round Neck T-sh... ",
  },

  {
    id: 26,
    image: "../../assets/p26.jpg",
    name: "Mast & Harbour  ",
    category: "tee shirt",
    price: 1200,
    discount_price: 599,
    description: "Men navy blue & pink printed henley neck T-shirt ",
  },
  {
    id: 27,
    image: "../../assets/p27.jpg",
    name: "Roadster ",
    category: "tee shirt",
    price: 1200,
    discount_price: 599,
    description: "Men navy blue Printed round neck T-shirt ",
  },
  {
    id: 28,
    image: "../../assets/p28.jpg",
    name: "bushirt",
    category: "tee shirt",
    price: 1200,
    discount_price: 599,
    description: "Men navy blue solid round neck T-shirt ",
  },
  {
    id: 29,
    image: "../../assets/p29.jpg",
    name: "Tommy Hilfiger",
    category: "tee shirt",
    price: 1200,
    discount_price: 599,
    description: "Men Navy Blue Printed Round Neck T-s... ",
  },
  {
    id: 30,
    image: "../../assets/p30.jpg",
    name: "H&M",
    category: "tee shirt",
    price: 1200,
    discount_price: 599,
    description: "Men black solid 3 Pack T-shirt slim fit ",
  },
];

export default Data;
